package org.oscelot.jshack.model;

import org.oscelot.jshack.resources.HackResource;

import java.util.List;
import java.util.Map;

/**
 * Created by wiley on 20/07/14.<br>
 * The HackRenderingContext encapsulates all the information required to render the hacks
 * in a RenderingHook at a given point in time.  It is generated by calling HackManager.getRenderingContext()
 */

public class HackRenderingContext {
    /** Resources to render on the page */
    private List<HackResource> resources;

    /** Map of config entries keyed by Hack ID */
    private Map<String, Map<String, String>> configEntryMap;

    /** Map of Resource URL entries keyed by Hack ID */
    private Map<String, Map<String, String>> resourceUrlMap;
}
